### ISSUE TITLE
Open refine model gives exception

### ISSUE THREAD

**Issue by nicky508** [fusepoolP3/p3-batchrefine#10]
I exported my Open Refine model to a .json file. After using it in batch refine I get this error:

org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

The Open Refine model consists of multiple root nodes enclosed with [ ]. A json validator validates the model correctly, but Batch refine seems to throw an exception on the firs [.

**Comment by andreybratus** [comment]
Could you please describe in more details how you use Batchrefine and how you submit the json rules? I need this to replicate the error.

**Comment by nicky508** [comment]
BatchRefine runs from docker, running the BatchRefine by using this line:

curl -XPOST -H "Content-Type:text/csv" -s turtle --data-binary @extract.csv "http://192.168.99.100:8310/?refinejson=http://10.0.0.6/skeleton.json"

Beginning of skeleton:

[
  {
    "op": "rdf-extension/save-rdf-schema",
    "description": "Save RDF schema skeleton",
    "schema": {
      "baseUri": "https://data.nfirs.fema.gov/",
      "prefixes": [
        {
          "name": "owl",
          "uri": "http://www.w3.org/2002/07/owl#"
        },
        {
          "name": "rdf",
          "uri": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        },
        {
          "name": "xsd",
          "uri": "http://www.w3.org/2001/XMLSchema#"
        },
        {
          "name": "rdfs",
          "uri": "http://www.w3.org/2000/01/rdf-schema#"
        },
        {
          "name": "foaf",
          "uri": "http://xmlns.com/foaf/0.1/"
        }
      ],

The json skeleton is published in an intern webserver.

I cannot publish the data and the skeleton since it is closed and sensitive data, sorry that would be easier.

**Comment by nicky508** [comment]
Seems that it struggles with the [] array structure of the file. If switch them for brackets { } it will load the skeleton, however throws a exception later on, that is cannot parse the json array.

**Comment by ktk** [comment]
Can you post the JSON file somewhere with a small sample input? IIRC the media-type of the file has to be provided properly, otherwise BatchRefine doesn't recognize it.

**Comment by nicky508** [comment]
Okay, the skeleton:             https://cloudbox.netage.nl/f/72dbfa6c46/?dl=1
little subset of the csv:        https://cloudbox.netage.nl/f/33ecbdc426/?dl=1

**Comment by andreybratus** [comment]
Thank you fro the sample data, I will test it ASAP. 
However, your skeleton1.json surprised me, it is 9.4 Mb in size. To be honest it is the first time I see a use case with such a big Rules/skeleton file.

**Comment by nicky508** [comment]
True, it is a quite big csv file with lots of columns and because some data inconsistencies we have to use all lot of root notes instead of collecting them together under one root note.

**Comment by andreybratus** [comment]
Apparently the issue is related to the size of the json file. Transformation rules are uploaded to OpenRefine as `application/x-www-form-urlencoded` and it appears there is a limit on its size;

```
15:52:52.721 [          org.mortbay.log] /command/core/apply-operations (2ms)
java.lang.IllegalStateException: Form too large8681590>1048576
	at org.mortbay.jetty.Request.extractParameters(Request.java:1560)
	at org.mortbay.jetty.Request.getParameter(Request.java:858)
	at com.google.refine.commands.Command.getProject(Command.java:171)
```

I think this should be configurable in Jetty, but have to check it.

**Comment by nicky508** [comment]
Ah ok, I will try to lighten my skeleton.

**Comment by nicky508** [comment]
Ok I was able to redesign the model. This new skeleton is only 3.8 mb: https://cloudbox.netage.nl/f/35c434e2bf/?dl=1 a lot smaller. However, I get the same error, could this be the same problem?

**Comment by nicky508** [comment]
Ok, I deleted the whole history out of the skeleton now the problem is gone and the skeleton is now 700 kb or something. So the solution is the delete the complete history which is all saved together in the same file.
