### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by mainini** [fusepoolP3/p3-batchrefine#3]
Please change the default port for the transformer and everything related to it (especially the docker-container) to the new default port 8310 according to https://github.com/fusepoolP3/overall-architecture/blob/master/default-ports.md .

Also, please commit a new image with the new default port to dockerhub.

Thanks a lot!

**Comment by andreybratus** [comment]
Default port changed to 8310. Dockerhub is also updated.

`docker run -p 8310:8310 fusepool/p3-batchrefine`
