### ISSUE TITLE
BatchRefine should use RDF as default output type

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-batchrefine#4]
If there is no specific output type requested BatchRefine seems to do CSV, see https://github.com/fusepoolP3/p3-dashboard/issues/14. This should be RDF instead.

**Comment by gmega** [comment]
The main problem here is that if the transform JSON does not provide an RDF mapping, then there's no way to honour such default (i.e., it wouldn't really be a default). The alternative is to output RDF by default if there is an RDF mapping, or CSV if there is none, but this IMHO goes against the principle of least surprise.

**Comment by ktk** [comment]
Good point, what do we do?

**Comment by gmega** [comment]
A quick-and-dirty solution would be to have a hidden option to start the transformer in "force RDF" mode which just removes everything that's not RDF from the allowed outputs. The caveat is that a JSON with an invalid mapping will create blank RDF as a response. If you think this makes sense, we can provide a fix in very little time.

**Comment by ktk** [comment]
Issue in Jira: https://fusepool.atlassian.net/browse/FP-370

**Comment by gmega** [comment]
Fair enough, that looks like The Right Way (tm) to me.

**Comment by retog** [comment]
with version v1.0.0-20151016 the proxy resolves FP-370. A build of the reference implementation has been triggered. Closing this issue as no action needed here atm.

**Comment by ktk** [comment]
Should sandbox contain this version? Because I just tried with my BatchRefine transformation and I still get CSV and not RDF.

**Comment by retog** [comment]
Please try again in a few minutes . If it still doesn't work check the
network traffic .

**Comment by ktk** [comment]
Thanks, now it works!
